version: "3.8"
services:
  springboot-app:
    image: thiernos/springboot-app:1.0   
    deploy:
      replicas: 8 
      restart_policy:
        condition: any
      update_config: 
        parallelism: 2
        delay: 10s
      rollback_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.role == worker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    networks:
      - springboot-net
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: P@ssw0rd123
      MYSQL_PORT: 3306
    restart: always

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - app-volume:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - springboot-net
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_ROOT_PASSWORD: P@ssw0rd123
    restart: always

volumes:
  app-volume:
    driver: local
networks:
  springboot-net:
    driver: overlay
