version: "3"
services:
  springboot-app:
    image: thiernos/springboot-app:1.0
    container_name: springboot-app
    restart: always
    build: .
    ports:
      - "8080:8080"
    networks:
      - springboot-net
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: P@ssw0rd123 
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - app-volume:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - springboot-net
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_ROOT_PASSWORD: P@ssw0rd123

volumes:
  app-volume:
    driver: local
networks:
  springboot-net:
    name: springboot-net
    driver: bridge
